name: Execultando teste da papiline
on: [push]

jobs: 
  Web-Teste:
    runs-on: ubuntu-20.04
    name: instando o sistema operacional

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalação do python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Instalação do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.1"

      - name: Instalação do Robot
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt


      - name: Executar os testes
        run: |
          robot tests/CriacaoDeConta.robot
                