name: Execultando teste da papiline
on: [push]

jobs: 
  Web-Teste: 
    runs-on: ubuntu-20.04
    name: instando o sistema operacional
    permissions: write-all
    # "Checkout" cria uma clone dos arquivos no repositório
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalação do python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Instalação do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.1"

      - name: Instalação do Robot
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Executar os testes
        run: |
          robot -d ./logs  -v BROWSER:headlesschrome  tests/CriacaoDeConta.robot

      - name: Exportando relatório
        if: always()
        uses: actions/upload-artifact@v3
        with: 
          name: result-tests-chrome
          path: ./logs
          if-no-files-found: ignore     
          retention-days: 4

      - name: Download do relatório de testes
        if: always()
        uses: actions/download-artifact@v1
        with: 
          name: result-tests-chrome         

      - name: Send Report
        if: always()
        uses: joonvena/robotframework-reporter-action@v2.4
        with: 
          report_path: result-tests-chrome
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          #show_passed_tests: false   